# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eed7d9973cf7f7929563135ef1ad2c9dc3f4e7f3860a22ea9cba5748728619f587bb14400405f33b16137bb2e909560bf32d8b4eaee8a2489c6606328694ebd1

test:
  secret_key_base: 01b7e7e780eff3a921de2dead5fc432baa4088715d4eb14ecece3dbe71653b87d38b471c44c6a05941f6eeee68801fce5f25ee0e9397747162b837e3bb476f71

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
